### ISSUE TITLE
How to process dijkstra shortest path parents that return #undef?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/Graphs.jl#140]
This may be a more general Julia question, but I'm at a loss as to how to treat something like this:
```
h = graph(["a","b","c","d"],[])
add_edge!(h,"a","b"); add_edge!(h,"b","c"); add_edge!(h,"a","c"); add_edge!(h,"c","d")


julia> dijkstra_shortest_paths(h,"b").parents
4-element Array{ASCIIString,1}:
 #undef
    "b"
    "b"
    "c"
```
How do I test for this `#undef` in code?
Also, more of an enhancement request, I guess - is there ANY way to get Graphs to return something consistent when a node is not reachable? That is, strings return `#undef`, ints return either some very large number or `0` (not sure why):

```
julia> dijkstra_shortest_paths(g,2).parents
4-element Array{Int64,1}:
 140253310593744
               2
               2
               3
...

julia> dijkstra_shortest_paths(g,2).parents
4-element Array{Int64,1}:
 0
 2
 2
 3

``` 
and I'm not quite sure how to test for all these cases other than checking to see whether the value is in `graph.vertices`, which apparently fails with `ERROR: access to undefined reference` if the value is `#undef`...

**Comment by yeesian** [comment]
Is `Nullable` only available in base julia 0.4?

**Comment by mlubin** [comment]
yes

**Comment by mlubin** [comment]
Or we can just use a simple bool array to indicate if a parent has been set or not.

**Comment by yeesian** [comment]
Yeah, I was thinking the same thing, at least for older versions of Julia
