### ISSUE TITLE
Decision: should per-vertex summary functions return dict, array, or other?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/Graphs.jl#142]
For discussion and decision:

Right now, `dijkstra_shortest_paths_explicit()` and others return an array whose indices match vertex indices. This is a reasonable way to associate the return values of a function with a particular vertex but makes the results a bit unintuitive.

Another reasonable way of doing this is to use a Dict mapping the actual vertex to the return value. The disadvantage here is that the key types will depend on the vertex types, and (re)associating them with other data will require calls to, e.g., `vertex_index`.

Which approach is preferable? I'd like to be consistent as I work on centrality measures, which associate a (`Float64`, usually) measure per vertex.

**Comment by yeesian** [comment]
Since this was [brought up again](https://github.com/JuliaLang/Graphs.jl/pull/146/files#r22419139), I should mention that in many usecases, per vertex summary functions (I'm really thinking of `enumerate_paths`) only operate on a small subset of vertices, and I think a `Dict` is pretty reasonable

**Comment by sbromberger** [comment]
If you know the subset, wouldn't it be just as easy to map it to the output? Dict may provide a convenience function but at the expense of consistency.

**Comment by yeesian** [comment]
Ah yeah, you're right; I stand corrected (:

**Comment by sbromberger** [comment]
I think all the experts polled here (and I'm specifically NOT counting myself in the list) have eventually decided in favor of vector-based results. Closing this out since we appear to have a consensus.
