### ISSUE TITLE
RFC: graph generators

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/Graphs.jl#157]
Hi all,

I had a need for a couple of graph generators so I went ahead and implemented most of the small graph generators in NetworkX (http://networkx.github.io/documentation/networkx-1.9.1/_modules/networkx/generators/small.html).

Would these be suitable for inclusion in Graphs.jl or should I consider a separate package? Currently implemented (returning `simple_graph` only):

- complete
- star
- path
- wheel
- diamond
- bull
- Chvatal
- cubical
- Desargues
- dodecahedral
- Frucht
- Heawood
- house / house-X
- icosahedral
- Krackhardt
- Moebius-Kantor
- octahedral
- Pappus
- Petersen
- Sedgewick maze
- tetrahedral
- truncated cube
- truncated tetrahedron
- Tutte

Happy to do whatever the team thinks is best.

**Comment by pozorvlak** [comment]
Cool! The consensus of a previous discussion was that any graph-generators which required extra statistical dependencies should go in https://github.com/arnim/RandomGraphs.jl, but I think we'd be happy to have everything else in Graphs.jl.

**Comment by sbromberger** [comment]
No dependencies. They're static graphs composed of known edges. Does this mean they go here?

**Comment by pozorvlak** [comment]
Sounds like it to me.

**Comment by sbromberger** [comment]
OK, great. I'll finish up docs and tests and submit a PR. Thanks!

**Comment by sbromberger** [comment]
Closing out since these have been merged.
