### ISSUE TITLE
RFC: JuliaGraphs organization

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/Graphs.jl#165]
Given that there are several graph-related packages either in METADATA or in development, and each serves a different purpose, would it make sense to create an organization that would serve as the go-to place for folks looking for specific functionality?

(came up in discussion with @yeesian and I figured it'd be worth polling the experts.)

**Comment by pozorvlak** [comment]
I'm not an expert, but that makes sense to me.

**Comment by johnmyleswhite** [comment]
That seems like a good idea to me.

**Comment by sbromberger** [comment]
I went ahead and created it, but will let the experts curate.

**Comment by sbromberger** [comment]
Actually, reopening so we can have discussion on the best way to use it.

**Comment by sbromberger** [comment]
So, it seems as if there hasn't been any objection to this proposal from the folks who have responded. I think we still need input from @lindahua and @mlubin so mentioning them here.

The organization has been created (https://github.com/JuliaGraphs). Once I hear a "go ahead" I'm happy to pull LightGraphs.jl into this new org but don't want to do anything before folks have had a chance to discuss/object.

**Comment by mlubin** [comment]
No objection here.

**Comment by sbromberger** [comment]
I transferred GraphCentrality over today. Still haven't heard from @lindahua as to whether he likes this proposal.

Also copying in @StefanKarpinski since I think there may be some copyright issue relating to the Julia logo - I modified it a bit (notice that it looks like a graph now) but want to make sure we're in the clear with respect to its use.

**Comment by StefanKarpinski** [comment]
You have to ask for permission to use the Julia logo – which I grant you. Thanks for asking!

**Comment by sbromberger** [comment]
It's been several months since this issue was opened, and JuliaGraphs is up and running. Obviously I'd love to see more folks contributing repos in there, but it doesn't make sense to keep this open in the hopes that Graphs.jl will be transferred. If the maintainers are interested in joining JuliaGraphs, just let me know - happy to add.

**Comment by tkelman** [comment]
@sbromberger I think we should move this repo over to JuliaGraphs. Can you invite some of the top contributors to this package to the JuliaGraphs organization, along with @scidom who expressed an interest a few months ago in helping with maintenance here? I can do the repo move if you grant me admin access to JuliaGraphs (temporarily if you prefer). Thanks!

**Comment by scidom** [comment]
Thanks @tkelman, yes, I have a long-term interest in the Graphs package because Lora relies on it; maintenance is still part of my overall set of goals, though slipped down my overloaded todo list... please keep me involved by all means, and I will try to push Graphs' maintenance higher in my habit tracker software, to attend to it if possible...

**Comment by dehann** [comment]
Hi @tkelman @scidom, I also have a longer term interest in the Graphs.jl package; for [IncrementalInference.jl](https://github.com/dehann/IncrementalInference.jl), a work in progress package. I will try help as things come up. I'm actually looking into adding user defined data to the ExVertex type as we speak. cc @GearsAD

**Comment by sbromberger** [comment]
@tkelman I am reluctant to make this move right now for several reasons. Graphs.jl has seen no significant activity in over a year; there are bugs that have remain unaddressed for nearly that long, and all indications are that the original maintainers are no longer interested in developing the package. I don't think it's a good candidate for inclusion right now, but if there is a commitment to active development as shown by an active commit log, I'm happy to revisit. 

I'm trying to avoid the problems we had with JuliaWeb where significant effort was spent gathering packages into a common org just to pull many of them out after the realization that they were in disrepair.
