### ISSUE TITLE
Feature request: Min Cut

### ISSUE THREAD

**Issue by bdeonovic** [JuliaLang/Graphs.jl#168]
Requesting min cut algorithm implementation for Graphs.jl

Stoer, Mechthild and Frank Wagner, “A simple min-cut algorithm”. Journal of the ACM 44 (4), 585-591, 1997. DOI: 10.1145/263867.263872

**Comment by kmsquire** [comment]
This would be quite useful!  Unless someone steps up soon, however, the best way for this to happen would be to try to implement it yourself, and submit a pull request.

**Comment by bdeonovic** [comment]
This has been implemented, it can be closed.
