### ISSUE TITLE
plot --> Linux

### ISSUE THREAD

**Issue by nsabic** [JuliaLang/Graphs.jl#176]
Hi, does anyone know why this happens when I want to plot a directed graph?
I'm using IJulia notebook (Python3) on Ubuntu 14.10. and I have already installed graphviz...  

`to_dot` has no method matching to_dot(::GenericGraph{Int32,Edge{Int32},UnitRange{Int32},Array{Edge{Int32},1},Array{Array{Edge{Int32},1},1}}, ::Pipe)
while loading In[23], in expression starting on line 1

 in plot at /home/nives/.julia/v0.3/Graphs/src/dot.jl:86

**Comment by jagrafft** [comment]
I am getting the same error on a Windows 8 system in Julia REPL and IJulia.

Once I switched the `neato -T` flag ([Issue 172](https://github.com/JuliaLang/Graphs.jl/issues/172)) I immediately received

```julia
`to_dot` has no method matching to_dot(::GenericGraph{Int64,Edge{Int64},UnitRange{Int64},Array{Edge{Int64},1},Array{Array{Edge{Int64},1},1}}, ::Pipe)
while loading In[4], in expression starting on line 1

 in plot at C:\Users\[user]\.julia\v0.3\Graphs\src\dot.jl:87
```

Currently line 87 in `dots.jl` is set to

```julia
stdin, proc = open(`neato -Tpng`, "w")
```

which should not be a problem on my system.

**Comment by nsabic** [comment]
Change line 88 in dot.jl like this:
to_dot(g, stdin, AttributeDict())
It should be fixed after that :)

**Comment by jagrafft** [comment]
I bet!

</
jgrafft@gmail.com
/>
