### ISSUE TITLE
LoadError: UndefVarError: with Serializer not defined (Graphs 0.5.4)

### ISSUE THREAD

**Issue by dehann** [JuliaLang/Graphs.jl#179]
Hi,

I should have a faily standard Julia setup (Ubuntu 12.04, gcc 4.6), and already using a few packages -- I seem to have an issue with just loading the Graphs package. I have removed and reinstalled it, but still did not fix the issue:

Any ideas?

Thanks

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3472 (2015-02-20 05:10 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 8c87a32* (88 days old master)
|__/                   |  x86_64-linux-gnu

julia> Pkg.status("Graphs")
 - Graphs                        0.5.4

julia> using Graphs
ERROR: LoadError: LoadError: LoadError: UndefVarError: Serializer not defined
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:54
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
while loading /home/dehann/.julia/DataStructures/src/hashdict.jl, in expression starting on line 11
while loading /home/dehann/.julia/DataStructures/src/DataStructures.jl, in expression starting on line 61
while loading /home/dehann/.julia/Graphs/src/Graphs.jl, in expression starting on line 2

**Comment by dehann** [comment]
Maybe something similar to issue#84, but I haven't been able to find it:

https://github.com/JuliaLang/Color.jl/issues/84

**Comment by mlubin** [comment]
0.4-dev from February is probably too old at this point. Package authors haven't really been maintaining backwards compatibility with the multiple breaking changes that have been taking place in 0.4.

**Comment by dehann** [comment]
Hi Miles,

Okay thanks -- the stable release 0.3.8 is working.

Version 0.3.8 (2015-04-30 23:40 UTC)

best
