### ISSUE TITLE
adjacency_matrix not working on edgelist graph

### ISSUE THREAD

**Issue by onlyhalfwaytrue** [JuliaLang/Graphs.jl#189]
##Vertices
julia> a = KeyVertex(1,"a")
KeyVertex{ASCIIString}(1,"a")

julia> b = KeyVertex(2,"b")
KeyVertex{ASCIIString}(2,"b")

julia> c = KeyVertex(3,"c")
KeyVertex{ASCIIString}(3,"c")

##Edges
julia> x1 = Edge(1,a,b)
edge [1]: KeyVertex{ASCIIString}(1,"a") -- KeyVertex{ASCIIString}(2,"b")

julia> x2 = Edge(2,b,c)
edge [2]: KeyVertex{ASCIIString}(2,"b") -- KeyVertex{ASCIIString}(3,"c")

julia> x3 = Edge(3,c,a)
edge [3]: KeyVertex{ASCIIString}(3,"c") -- KeyVertex{ASCIIString}(1,"a")

##VertexSet and EdgeSet
julia> vs = {a,b,c}
3-element Array{Any,1}:
 KeyVertex{ASCIIString}(1,"a")
 KeyVertex{ASCIIString}(2,"b")
 KeyVertex{ASCIIString}(3,"c")

julia> es = {x1,x2,x3}
3-element Array{Any,1}:
 edge [1]: KeyVertex{ASCIIString}(1,"a") -- KeyVertex{ASCIIString}(2,"b")
 edge [2]: KeyVertex{ASCIIString}(2,"b") -- KeyVertex{ASCIIString}(3,"c")
 edge [3]: KeyVertex{ASCIIString}(3,"c") -- KeyVertex{ASCIIString}(1,"a")

##Graph
julia> g = edgelist(vs,es,is_directed=false)
Undirected Graph (3 vertices, 3 edges)

##ERROR
julia> adjacency_matrix(g)
ERROR: `source` has no method matching source(::Edge{KeyVertex{ASCIIString}}, ::GenericEdgeList{Any,Any,Array{Any,1},Array{Any,1}})
 in matrix_from_adjpairs! at /Users/ja26144/.julia/v0.3/Graphs.jl/src/gmatrix.jl:21
 in matrix_from_adjpairs at /Users/ja26144/.julia/v0.3/Graphs.jl/src/gmatrix.jl:47
 in adjacency_matrix at /Users/ja26144/.julia/v0.3/Graphs.jl/src/gmatrix.jl:242

**Comment by onlyhalfwaytrue** [comment]
Edgelist was allowing me to use an Any type array to create the graph but adjacency_matrix was not allowing it to work without a vector of KeyVertex types.

**Comment by jackiemauro** [comment]
Can you post the code that solved the issue? I'm having a similar one.
