### ISSUE TITLE
Need multiple minimal paths returned by Dijkstra algorithm

### ISSUE THREAD

**Issue by irving0p0rabin** [JuliaLang/Graphs.jl#193]
I am using dijkstra_shortest_paths method as a base of calculating betweenness centrality. In my case all the weights are 1.0, so the shortest path is literally the shortest - with the smallest number of nodes between. My problem is that I want to see all shortest paths - so if there are 3 paths between A and B with the shortest length (say 5), then I want to be able to see all paths between A and B with length 5. Is it possible?

**Comment by sbromberger** [comment]
@irving0p0rabin you might look at GraphCentrality.jl which has betweenness_centrality already defined for Graphs. A much faster implementation is in LightGraphs.jl as well.
