### ISSUE TITLE
adjlist doesn't create adjlist for each vertices passed in

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/Graphs.jl#209]
My first ever use of `Graphs.jl` gives the following error.

```{julia}
g = adjlist([1,2])
add_edge!(g, 1, 2)
# BoundsError
```
I think `adjlist{V}(vs::Vector{V}; is_directed::Bool=true) = AdjacencyList{V}(is_directed, vs, 0, Vector{V}[])` in 
(https://github.com/JuliaLang/Graphs.jl/blob/master/src/adjacency_list.jl#L29) is not correct as `AdjacencyList.AdjList` is not fully initialized with the vertices in `vs`.

Forgive me if I misunderstand the usage, and I will submit a PR if someone can help confirm the issue.

**Comment by weijianzhang** [comment]
@colinfang I think you are right. It is a bug.
