### ISSUE TITLE
Graphs should not die, I need it (and I think I am not the only one!)

### ISSUE THREAD

**Issue by scidom** [JuliaLang/Graphs.jl#218]
I have noticed that `Graphs` is not maintained anymore, to the point that issues or PRs remain open and unanswered for weeks or months. I would like to volunteer to contribute a bit to the package, simply because it is important to me (Lora heavily relies on it), and because I am not planning to migrate to `LightGraphs` (for the simply reason that the main graph types in `Graphs` work better with my problem at hand).

Is there any chance someone could give me admin access? I can do a bit of housekeeping, at least to ensure that the package remains alive, definitely better than seeing the package dying a slow death...

cc @yuyichao @kmsquire @mlubin

**Comment by mlubin** [comment]
CC @StefanKarpinski @ViralBShah 
I don't think I have the ability to give you admin access.

**Comment by dehann** [comment]
I agree! I'm starting to push new packages into the Julia ecosystem as we speak, and one of them relies heavily on Graphs.jl [IncrementalInference.jl](https://github.com/dehann/IncrementalInference.jl). FYI -- I'm still busy developing this package, and been toying with the idea of extending Graphs.jl to contain extra information in it's types. I'm building factor graphs and junction trees (currently abusing the ExVertex.attributes dictionary for data storage).
cc @scidom @mlubin

**Comment by kmsquire** [comment]
+1.  I also do not have the ability to give you admin access.  

My commitments have led me in other directions, and I haven't needed Graphs.jl for anything recently.  That said, if there are outstanding PRs for things you need, or if you create any before you get commit access, ping me.

**Comment by scidom** [comment]
Happy to see that there are several of us that find Graphs useful. Of course, I would seek feedback before any critical PRs or issues. I am also overloaded with work, but I can at the very least do some minor housekeeping taking care of more trivial issues and ensure continued flow of communication between all of us; there are issues open for months, and I thought developers would be happy to see their issues or PRs progressing, and more generally the github pulse active.

**Comment by dehann** [comment]
cc @tedsteiner

**Comment by tkelman** [comment]
I think if maintenance is going to pick back up here, we should revisit moving this to JuliaGraphs, ref https://github.com/JuliaLang/Graphs.jl/issues/165

**Comment by ViralBShah** [comment]
Is the ownership sorted now?

-viral

**Comment by scidom** [comment]
Thanks Viral; if not mistaken, I think it hasn't been sorted yet, as I don't see the option of merging PRs (neither the settings tab at the tob of the package repo), if these are indicators of write access.

**Comment by tkelman** [comment]
Which PR are you looking at? You shouldn't need admin access, just JuliaLang commit access at the moment which I think you already have.

**Comment by scidom** [comment]
Oh, great then. I didn't know that commit access has been sorted out. What I meant is that I randomly opened one of the PRs and didn't have any visual indication in the browser that sth has changed. I guess then I will simply be able to see that I have commit access when I do try to make any commits.

I will close this issue then, and will let you know if I still have any issues. Thanks @ViralBShah, @tkelman!
