### ISSUE TITLE
Syntax errors with the latest Julia

### ISSUE THREAD

**Issue by rsofaer** [JuliaLang/Graphs.jl#34]
Hi Dahua,

The latest Julia broke a few things.
It no longer likes this pattern of having W as both a type parameter and a parameter:

```
function default_prim_visitor{V,E,W}(g::AbstractGraph{V,E}, W::Type{W})    
    edges = Array(E, 0)
    weights = Array(W, 0)
    n = num_vertices(g)
    if n > 1
        sizehint(edges, n-1)
        sizehint(weights, n-1)
    end
    PrimVisitor{E,W}(edges, weights)
end
```

it gives this error:

```
syntax: function argument and static parameter names must be distinct
```

I started to fix it, but I didn't see a clear way forward so I figured I'd make an issue.  This might be for upstream if there needs to be a clearer way to do this.

**Comment by jingpengwu** [comment]
I still get this error with this code:
```
type ChunkStore{T,N} <: AbstractChunkStore
    kvStore     ::Associative
    chunkSize   ::NTuple{Int,N}
    function (::Type{ChunkStore}){dataType,N}( kv::Associative,
                                dataType::DataType, chksz::NTuple{Int,N})
        new{dataType,N}(kv, chksz)
    end
end
```
@lindahua could you please give a little bit more explanation of this error?
